#!/usr/bin/env bash

case $1 in "push")
	git add .
	git commit -m "$2"
	git push
	exit 1
;;
"create")
	echo "creating directory..."
	mkdir $2
	cd $2
	echo "Generated by NeoGit" >> README.md
	git init
	git add .
	git branch -M main
	git remote add origin "$3"
	git commit -m "Creation commit"
	git push -u origin main
	exit 1
;;
esac

git $*
